# Generated by Django 3.0.7 on 2021-06-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food', models.CharField(default='heno', max_length=200)),
                ('treadmil', models.CharField(default='si', max_length=200)),
                ('padock', models.CharField(default='si', max_length=200)),
                ('estado', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)),
                ('herradura', models.CharField(default='no', max_length=200)),
                ('director', models.ForeignKey(default='director', on_delete=django.db.models.deletion.CASCADE, related_name='director_id', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actividad', models.CharField(default='concurso ', max_length=300)),
                ('student', models.ForeignKey(default='student', on_delete=django.db.models.deletion.CASCADE, related_name='student_idddd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
