# Generated by Django 3.0.7 on 2021-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210608_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='food',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='herradura',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='padock',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='treadmil',
        ),
        migrations.AddField(
            model_name='prescription',
            name='sintomas',
            field=models.CharField(default='fiebre', max_length=200),
        ),
    ]
