# Generated by Django 3.0.7 on 2022-10-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210620_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_arbol',
            field=models.CharField(blank=True, choices=[('PALMA', 'PALMA'), ('BONSAI', 'BONSAI'), ('GIRASOL', 'GIRASOL')], max_length=7),
        ),
    ]
