# Generated by Django 3.0.7 on 2022-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_evento_tipo_arbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='actividad',
            field=models.CharField(choices=[('SIEMBRA', 'SIEMBRA'), ('RIEGO', 'RIEGO'), ('ABONO', 'ABONO')], default='interclases', max_length=7),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_arbol',
            field=models.CharField(blank=True, choices=[('PALMA', 'PALMA'), ('BONSAI', 'BONSAI'), ('GIRASOL', 'GIRASOL')], default='PALMA', max_length=7),
        ),
    ]
