# Generated by Django 3.0.7 on 2022-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20221029_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(choices=[('Parque', 'Parque'), ('Colegio', 'Colegio'), ('Universidad', 'Universidad'), ('Rural', 'Rural'), ('Barrio', 'Barrio'), ('Campo Deportivo', 'Campo Deportivo')], default='Parque', max_length=16),
        ),
    ]
