# Generated by Django 3.0.7 on 2022-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_auto_20221031_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='altura',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='barrio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='comuna',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='dap',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='diametro_copa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='familia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='recomendaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
