# Generated by Django 3.0.7 on 2022-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_auto_20221105_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_arbol',
            field=models.CharField(choices=[('PALMA', 'PALMA'), ('BONSAI', 'BONSAI'), ('GIRASOL', 'GIRASOL')], default='PALMA', max_length=7),
        ),
    ]
