# Generated by Django 3.0.7 on 2022-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20221105_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
