# Generated by Django 3.0.7 on 2023-02-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_auto_20221118_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='familia',
            new_name='al_cuarto_fuste',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_cientifico',
            new_name='al_primer_fuste',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_comun',
            new_name='al_segundo_fuste',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dap',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='diametro_copa',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='recomendaciones',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo_arbol',
        ),
        migrations.AddField(
            model_name='evento',
            name='al_tercer_fuste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='big_observaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='codigo_sigau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='especie_vegetal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_destoconado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_medicion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_recoleccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_trabajo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='manejo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='no_arbol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_concepto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='pe_cuarto_fuste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='pe_primer_fuste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='pe_segundo_fuste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='pe_tercer_fuste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='presencia_avifauna',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_manejo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_intervencion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
