# Generated by Django 3.0.7 on 2023-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_auto_20230204_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
