# Generated by Django 3.0.7 on 2021-06-17 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8, null=True)),
                ('nombre_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('nit_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('cumpleanos_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('email_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('grado_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('id_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('cumpleanos_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('email_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('trabajo_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('celular_acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('id_seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('identidad_seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_seguro', models.CharField(blank=True, max_length=50, null=True)),
                ('condicion_especial', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_condicion_especial', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
