# Generated by Django 3.0.7 on 2021-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20211128_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grado_estudiante',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('01A', '01 ACADEMICO'), ('02A', '02 ACADEMICO'), ('03A', '03 ACADEMICO'), ('04A', '04 ACADEMICO'), ('05A', '05 ACADEMICO')], default='1', max_length=3),
        ),
    ]
