# Generated by Django 3.0.7 on 2021-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20211128_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seccion_estudiante',
            field=models.CharField(blank=True, choices=[('1', '01'), ('2', '02'), ('3', '03')], default='1', max_length=1),
        ),
    ]
