# Generated by Django 3.0.7 on 2021-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userprofile_seccion_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jornada_estudiante',
            field=models.CharField(blank=True, choices=[('MANANA', 'MANANA'), ('TARDE', 'TARDE')], default='MANANA', max_length=6),
        ),
    ]
