# Generated by Django 3.0.7 on 2021-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_userprofile_jornada_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipodoc_estudiante',
            field=models.CharField(blank=True, choices=[('NIP', 'NIP'), ('NUIP', 'NUIP'), ('OTRO', 'OTRO'), ('R.C', 'R.C'), ('T.I', 'T.I')], default='T.I', max_length=4),
        ),
    ]
