# Generated by Django 3.0.7 on 2021-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20211128_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellido_2_estudiante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_2_estudiante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
