# Generated by Django 3.0.7 on 2021-11-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20211128_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='barrio_estudiante',
            new_name='telefono_estudiante',
        ),
    ]
