# Generated by Django 3.0.7 on 2021-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20211128_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellido_2_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_2_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
