# Generated by Django 3.0.7 on 2021-11-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20211128_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='trabajo_acudiente',
            new_name='ocupacion_mama',
        ),
    ]
