# Generated by Django 3.0.7 on 2021-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_auto_20211128_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parentesco_acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
