# Generated by Django 3.0.7 on 2022-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_auto_20211128_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='busqueda',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
